"""Generate docs/COMPENDIUM.md — the compendium in human-readable form, from the catalogue."""
from __future__ import annotations

import sqlite3
from pathlib import Path


def _children(conn: sqlite3.Connection, cid: str) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT c.id, c.label, c.scope_note, s.sitelinks, c.time_from, c.time_to,"
        " (SELECT group_concat(f.facet_id, ', ') FROM facet f WHERE f.concept_id = c.id) AS facets,"
        " (SELECT m.to_id || ' ' || m.relation FROM mapping m WHERE m.from_id = c.id AND m.to_id LIKE 'wd/%'"
        "   AND m.status = 'accepted') AS wd"
        " FROM broader b JOIN concept c ON c.id = b.child LEFT JOIN concept_stat s ON s.concept_id = c.id"
        " WHERE b.parent = ? AND c.status = 'active' ORDER BY c.id", (cid,)).fetchall()


def _line(r: sqlite3.Row, depth: int) -> str:
    bits = []
    if r["wd"]:
        bits.append(r["wd"])
    if r["sitelinks"] is not None:
        bits.append(f"{r['sitelinks']} Wikipedias")
    if r["facets"]:
        bits.append(r["facets"])
    if r["time_from"] is not None or r["time_to"] is not None:
        bits.append(f"years {r['time_from'] if r['time_from'] is not None else '…'} to "
                    f"{r['time_to'] if r['time_to'] is not None else '…'}")
    meta = f" <sub>`{r['id']}` · {' · '.join(bits)}</sub>" if bits else f" <sub>`{r['id']}`</sub>"
    note = f" — {r['scope_note']}" if r["scope_note"] else ""
    return f"{'  ' * depth}- **{r['label']}**{note}{meta}"


def write_compendium_md(conn: sqlite3.Connection, out: Path) -> int:
    built = conn.execute("SELECT value FROM meta WHERE key = 'built_at'").fetchone()
    roots = conn.execute(
        "SELECT c.id, c.label, c.scope_note, s.sitelinks, c.time_from, c.time_to, NULL AS facets,"
        " (SELECT m.to_id || ' ' || m.relation FROM mapping m WHERE m.from_id = c.id AND m.to_id LIKE 'wd/%'"
        "   AND m.status = 'accepted') AS wd"
        " FROM concept c JOIN concept_stat s ON s.concept_id = c.id WHERE c.scheme = 'acat' AND s.depth = 0"
        " AND c.status = 'active' ORDER BY c.id").fetchall()
    seeds = conn.execute("SELECT name, sha512 FROM source WHERE kind = 'seed' AND name LIKE 'seed/compendium/%'"
                         " ORDER BY name").fetchall()
    lines = [
        "# The ACAT Compendium",
        "",
        "> Generated by `acat compendium-md` from the catalogue database "
        f"(built {built[0] if built else 'unknown'}). Do not edit by hand: edit `seed/compendium/acat/*.tsv`.",
        "",
        "Thirteen domains arranged as a circle, not a ranking: they are listed by code only. Each entry shows",
        "its scoped id, its reviewed Wikidata match (if any), how many Wikipedia language editions cover that",
        "item (attention, not importance), its UN M49 region facets, and its world-time span in years",
        "(astronomical numbering: 1 BCE = 0).",
        "",
        "Seed files and their SHA-512:",
        "",
    ]
    lines += [f"- `{n}` — `{s[:32]}…`" for n, s in seeds]
    count = 0
    for r in roots:
        lines += ["", f"## {r['label']}", "", f"{r['scope_note'] or ''} <sub>`{r['id']}`"
                  + (f" · {r['wd']}" if r["wd"] else "") + "</sub>", ""]
        count += 1

        def walk(cid: str, depth: int) -> None:
            nonlocal count
            for ch in _children(conn, cid):
                lines.append(_line(ch, depth))
                count += 1
                walk(ch["id"], depth + 1)

        walk(r["id"], 0)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count
