"""In-place schema upgrades. Rows that must never be lost are copied, counted and hashed before any
table is rebuilt; derived structures (search indexes) are simply recreated by the next build.
Every migration is one ledger row with its receipt."""
from __future__ import annotations

import sqlite3

from . import ledger
from .util import sha512_bytes

LATEST = 4
DERIVED_VIEWS = ("v_claim_current", "v_claim_truthy", "v_claim_evidence")


def _has_table(conn: sqlite3.Connection, name: str) -> bool:
    return conn.execute("SELECT 1 FROM sqlite_master WHERE name = ?", (name,)).fetchone() is not None


def _rows_digest(conn: sqlite3.Connection, sql: str) -> tuple[int, str]:
    rows = conn.execute(sql).fetchall()
    body = "\n".join("\x1f".join("" if v is None else str(v) for v in r) for r in rows)
    return len(rows), sha512_bytes(body.encode("utf-8"))


def migrate(conn: sqlite3.Connection) -> list[str]:
    """Bring an existing catalogue up to LATEST. A new, empty database needs nothing."""
    if not _has_table(conn, "concept"):
        return []
    version = conn.execute("PRAGMA user_version").fetchone()[0]
    done = []
    if version < 2:
        _v1_to_v2(conn)
        done.append("1->2")
    if version < 3:
        _v2_to_v3(conn)
        done.append("2->3")
    if version < 4:
        _v3_to_v4(conn)
        done.append("3->4")
    return done


def _v3_to_v4(conn: sqlite3.Connection) -> None:
    """v4: a review can carry the relation a revision asks for."""
    conn.execute("BEGIN")
    try:
        n = 0
        if _has_table(conn, "review"):           # older databases get the whole table from schema.sql
            if "relation" not in {r[1] for r in conn.execute("PRAGMA table_info(review)")}:
                conn.execute("ALTER TABLE review ADD COLUMN relation TEXT")
            n = conn.execute("SELECT count(*) FROM review").fetchone()[0]
        ledger.record(conn, "acat migrate", "migrate-schema", target="schema",
                      detail={"from": 3, "to": 4, "review_columns_added": ["relation"], "reviews": n},
                      undo="restore the database file from before the migration, or rebuild it from seed/ and corpora/")
        conn.execute("PRAGMA user_version = 4")
        conn.commit()
    except BaseException:
        conn.rollback()
        raise


def _v2_to_v3(conn: sqlite3.Connection) -> None:
    """v3: integer day bounds on claims; review, baseline and audit tables (created by schema.sql).
    Only columns are added: no row is rewritten."""
    conn.execute("BEGIN")
    try:
        cols = {r[1] for r in conn.execute("PRAGMA table_info(claim)")}
        added = [c for c in ("valid_from_day", "valid_to_day") if c not in cols]
        for col in added:
            conn.execute(f"ALTER TABLE claim ADD COLUMN {col} INTEGER")
        n, digest = _rows_digest(conn, "SELECT id, subject, predicate, object, value, source_sha512, recorded_at"
                                       " FROM claim ORDER BY id")
        ledger.record(conn, "acat migrate", "migrate-schema", target="schema",
                      detail={"from": 2, "to": 3, "claim_columns_added": added, "claims": n,
                              "new_tables": ["review", "baseline", "audit_run", "audit_metric"]},
                      receipt=f"claims-sha512:{digest}",
                      undo="restore the database file from before the migration, or rebuild it from seed/ and corpora/")
        conn.execute("PRAGMA user_version = 3")
        conn.commit()
    except BaseException:
        conn.rollback()
        raise


def _v1_to_v2(conn: sqlite3.Connection) -> None:
    """v2: case-key search indexes, VACUUM-safe label ids, statement-level claims.

    - search indexes are derived: dropped here, recreated by schema.sql and filled by the build
    - labels are regenerated by every build, but copied so the database stays consistent meanwhile
    - claims are never deleted: every row is copied into the new table; the old import's mapping of
      Wikidata's deprecated rank to epistemic/superseded is undone (deprecated is the source's own
      rank, not a withdrawal by the source), and the ledger records how many rows that touched
    """
    conn.execute("PRAGMA foreign_keys = OFF")
    conn.execute("BEGIN")
    try:
        for trig in ("passage_ai", "passage_ad", "passage_au"):
            conn.execute(f"DROP TRIGGER IF EXISTS {trig}")
        for view in DERIVED_VIEWS:                   # views name the tables rebuilt below; schema.sql recreates them
            conn.execute(f"DROP VIEW IF EXISTS {view}")
        for t in ("concept_tri", "label_tri", "passage_tri", "label_fts", "concept_fts", "passage_fts"):
            conn.execute(f"DROP TABLE IF EXISTS {t}")

        n_labels, _ = _rows_digest(conn, "SELECT concept_id, lang, kind, text FROM label ORDER BY 1, 2, 3, 4")
        conn.execute("""CREATE TABLE label_v2 (
            id INTEGER PRIMARY KEY, concept_id TEXT NOT NULL REFERENCES concept(id), lang TEXT NOT NULL,
            kind TEXT NOT NULL CHECK (kind IN ('pref', 'alt', 'desc')), text TEXT NOT NULL,
            source_sha512 TEXT REFERENCES source(sha512), UNIQUE (concept_id, lang, kind, text))""")
        conn.execute("INSERT INTO label_v2(concept_id, lang, kind, text, source_sha512)"
                     " SELECT concept_id, lang, kind, text, source_sha512 FROM label ORDER BY rowid")
        conn.execute("DROP TABLE label")
        conn.execute("ALTER TABLE label_v2 RENAME TO label")

        n_claims, before = _rows_digest(conn, "SELECT id, subject, predicate, object, value, source_sha512,"
                                              " recorded_at FROM claim ORDER BY id")
        relabelled = conn.execute("SELECT count(*) FROM claim WHERE rank = 'deprecated'"
                                  " AND epistemic = 'epistemic/superseded'").fetchone()[0]
        conn.execute("""CREATE TABLE claim_v2 (
            id INTEGER PRIMARY KEY, subject TEXT NOT NULL, predicate TEXT NOT NULL,
            snak_type TEXT NOT NULL DEFAULT 'value' CHECK (snak_type IN ('value', 'somevalue', 'novalue')),
            object TEXT, value TEXT, datatype TEXT, qualifiers TEXT, rank TEXT, statement_id TEXT,
            source_revision INTEGER, source_pointer TEXT, epistemic TEXT NOT NULL DEFAULT 'epistemic/attributed',
            perspective TEXT, valid_from TEXT, valid_to TEXT, time_precision INTEGER,
            source_sha512 TEXT NOT NULL REFERENCES source(sha512), recorded_at TEXT NOT NULL, superseded_at TEXT,
            CHECK (snak_type <> 'value' OR ((object IS NULL) <> (value IS NULL))),
            CHECK (snak_type = 'value' OR (object IS NULL AND value IS NULL)))""")
        conn.execute("""INSERT INTO claim_v2(id, subject, predicate, snak_type, object, value, qualifiers, rank,
                            epistemic, perspective, valid_from, valid_to, source_sha512, recorded_at, superseded_at)
                        SELECT id, subject, predicate, 'value', object, value, qualifiers, rank,
                            CASE WHEN rank = 'deprecated' AND epistemic = 'epistemic/superseded'
                                 THEN 'epistemic/attributed' ELSE epistemic END,
                            perspective, valid_from, valid_to, source_sha512, recorded_at, superseded_at
                        FROM claim ORDER BY id""")
        n_after, after = _rows_digest(conn, "SELECT id, subject, predicate, object, value, source_sha512,"
                                            " recorded_at FROM claim_v2 ORDER BY id")
        if (n_after, after) != (n_claims, before):
            raise RuntimeError("claim copy does not match the original rows; nothing was changed")
        conn.execute("DROP TRIGGER IF EXISTS claim_never_deleted")
        conn.execute("DROP INDEX IF EXISTS claim_identity")
        conn.execute("DROP TABLE claim")
        conn.execute("ALTER TABLE claim_v2 RENAME TO claim")
        ledger.record(conn, "acat migrate", "migrate-schema", target="schema",
                      detail={"from": 1, "to": 2, "labels_copied": n_labels, "claims_copied": n_claims,
                              "deprecated_rank_restored_to_attributed": relabelled,
                              "search_indexes": "dropped; rebuilt by the next build"},
                      receipt=f"claims-sha512:{before}",
                      undo="restore the database file from before the migration, or rebuild it from seed/ and corpora/")
        conn.execute("PRAGMA user_version = 2")
        conn.commit()
    except BaseException:
        conn.rollback()
        raise
    finally:
        conn.execute("PRAGMA foreign_keys = ON")
